wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.7
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723986052
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      3:
      - 23
      4: 3.9.19
      5: 0.17.7
      6: 4.44.0
      8:
      - 5
      13: linux-x86_64
